
parameters:
  file_path: tmp/{0}.tsv.gz

definitions:

  titles:
    url: https://datasets.imdbws.com/title.basics.tsv.gz
    filter:
      titleType:
        - short
        - movie
        - tvMovie
        - tvShort
        - tvSpecial
        - video
    columns:
      tconst: movie
      titleType: type
      primaryTitle: title
      startYear: year
      runtimeMinutes: duration
      genres: genres

  ratings:
    url: https://datasets.imdbws.com/title.ratings.tsv.gz
    columns:
      tconst: movie
      averageRating: rating
      numVotes: votes

  names:
    url: https://datasets.imdbws.com/name.basics.tsv.gz
    columns:
      nconst: person
      primaryName: name
      knownForTitles: major_titles

  crew:
    url: https://datasets.imdbws.com/title.crew.tsv.gz
    columns:
      tconst: movie
      directors: directors
      writers: writers

  principals:
    url: https://datasets.imdbws.com/title.principals.tsv.gz
    filter:
      category:
        - writer
        - actress
        - actor
        - director
        - producer
        - composer
    columns:
      tconst: movie
      nconst: person
      category: role
