
nb_results: 5

url:
  root: https://www.imdb.com/search/title?title={search_string}&title_type={types_string}&num_votes={min_votes},&count=50
  types:
    - feature
    - tv_movie
    - tv_special
    - documentary
    - short
    - video
    - tv_short
  min_votes: 1000

content:
  tag: div
  type: id
  key: main

rows:
  tag: div
  type: class
  key: mode-advanced

find:

  title:
    params:
      - tag: h3
      - tag: a
    apply:
      - func: lib.apply_functions.get_text

  movie:
    params:
      - tag: h3
      - tag: a
    apply:
      - func: lib.apply_functions.get_url

  genres:
    params:
      - tag: span
        type: class
        key: genre
    apply:
      - func: lib.apply_functions.get_text
      - func: lib.apply_functions.strip
        args:
          - " ,\t\n\r\xa0"

  year:
    params:
      - tag: span
        type: class
        key: lister-item-year
    apply:
      - func: lib.apply_functions.get_text

  staff:
    params:
      - tag: div
        type: class
        key: lister-item-content

  image:
    params:
      - tag: div
        type: class
        key: lister-item-image
      - tag: img
    apply:
      - func: lib.apply_functions.get_image_url

images:
  split_on: "._"
  version_str: "V1_UX182_CR0,0,182,268_AL_.jpg"
