
url_search: http://www.imdb.com/find?q={}&s=tt&ttype=ft&ref_=fn_ft

content:
  tag: div
  type: id
  key: main

find:
  first_results:
    params:
      - tag: table
        type: class
        key: findList
      - tag: td
        type: class
        key: result_text
        multiple: True
      - tag: a
    format: link